name: go-mod-fix
on:
  push:
    branches:
      - renovate/*

jobs:
  go-mod-fix:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 2
      - name: fix
        uses: at-wat/go-sum-fix-action@3dc8f2920db3f273c17a92424e1dc5f568163733 # v0.8.9
        with:
          git_user: github-actions[bot]
          git_email: 41898282+github-actions[bot]@users.noreply.github.com
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_style: squash
          push: force
