---
name: Lizard Runner
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lizard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Lizard Runner
        uses: Uno-Takashi/Lizard-Runner@84be77b3a59d9a98a74c46018adfbd5110dc9744 # v3
